services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Маппинг портов 8080:80 для работы через nginx reverse proxy
      - "8080:80"
      # - "443:443"
    volumes:
      - /etc/ssl/cloudflare/a-t-group.ru:/etc/ssl/cloudflare/a-t-group.ru:ro
    environment:
      - VITE_TELEGRAM_BOT_TOKEN=${VITE_TELEGRAM_BOT_TOKEN}
      - VITE_TELEGRAM_CHAT_ID=${VITE_TELEGRAM_CHAT_ID}
      - VITE_STRAPI_API_URL=http://strapi:1337
    restart: unless-stopped
    # Опционально: можно добавить имя контейнера для удобства
    container_name: alextrans_app
    networks:
      - alextrans-network

networks:
  alextrans-network:
    driver: bridge 