version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Маппинг на порт 8080, так как порт 80 уже занят
      - "8080:80"
      # Порт для HTTPS, раскомментируйте при настройке SSL
      # - "443:443"
    volumes:
      - /etc/ssl/cloudflare/a-t-group.ru:/etc/ssl/cloudflare/a-t-group.ru:ro
    environment:
      - VITE_TELEGRAM_BOT_TOKEN=${VITE_TELEGRAM_BOT_TOKEN}
      - VITE_TELEGRAM_CHAT_ID=${VITE_TELEGRAM_CHAT_ID}
      - VITE_STRAPI_URL=https://strapi.a-t-group.ru
    restart: unless-stopped
    container_name: alextrans_app 